"""Create url_map table

Revision ID: 370057ca644f
Revises: 
Create Date: 2024-08-16 07:33:00.568894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370057ca644f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('short_url', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_map', schema='public')
    # ### end Alembic commands ###
